c   pointers.h
c
c   ponteiros para os arranjos chamados com frequencia no ciclo Newton
c   para o calculo das forcas internas em regime elastoplastico
c
c   inclui tambem ponteiros dos arranjos para impressao de resultados 
c
c
c   ponteiros definidos e/ou localizados na rotina pre_plas e nldriver
c

      common / pointers /	nsig,ndsig,ntau,ndeps,nprop,nmtype,niplast,
     &						nx,ny,nz,nincid,nft,nuniax,nratio,nnsub,nfe,ndu,nlm,
     &						nid,ndisp,nsg0,npnode,ndpnode,npls,niedge,ninc,nmaxa,
     &						nstiff              

